# Setup
title:        TCP Bros
tagline:      Tecnología ciencia y programación
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Oscar Arbeláez
  url:        https://tcpbros.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
